# Generated by Django 4.1.3 on 2022-11-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="category",),
        migrations.RemoveField(model_name="news", name="region",),
        migrations.RemoveField(model_name="news", name="status",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="News",),
        migrations.DeleteModel(name="Region",),
        migrations.DeleteModel(name="Status",),
    ]
