# Generated by Django 4.1.3 on 2022-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="updatedon",),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Politics", "Politics"),
                    ("Education", "Education"),
                    ("Health", "Health"),
                    ("Business", "Business"),
                    ("Sports", "Sports"),
                    ("Entertainment", "Entertainment"),
                    ("Technology", "Technology"),
                    ("Science", "Science"),
                    ("Travel", "Travel"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="news", name="createdby", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="news", name="createdon", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="news",
            name="region",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("National", "National"),
                    ("International", "International"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Draft", "Draft"),
                    ("Approved", "Approved"),
                    ("Published", "Published"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Region",),
        migrations.DeleteModel(name="Status",),
    ]
